#!/bin/bash
if [ -z "$VERSION" ]; then 
    VERSION=`cat VERSION` 
fi
if [ -z "$IMAGE_NAME" ]; then 
    IMAGE_NAME="sangram/alpine-maildev:$VERSION"
fi


docker build --rm --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg VCS_REF=`git rev-parse --short HEAD` \
            --build-arg VERSION=$VERSION \
            -t $IMAGE_NAME .